### ISSUE TITLE
Habilitar Cross-origin resource sharing 

### ISSUE THREAD

**Issue by sgobotta** [facttic/recumap-backend#16]
Deberíamos encontrar una manera de habilitar pedidos desde un origen particular, o habilitar todos por el momento.
Hay un PR abierto con un ejemplo, la cuestión es replicar el `options` preflight en los pedidos que el frontend necesita, que me parece que son todos. Quizas haya mejores prácticas que poner options en cada endpoint.

**Comment by pehuen-rodriguez** [comment]
Fuimos con el PR. Si por ahora funca, meta con esa. Cuando haya oportunidad, le preguntamos a Pablo.
